### ISSUE TITLE
clarify role and difference between pypam and pamguard

### ISSUE THREAD

**Issue by LennertSchepers** [lifewatch/pypam#105]
Hi all
I heard from an open software called Pamguard: https://github.com/PAMGuard/PAMGuard and [www.pamguard.org/](http://www.pamguard.org/). It might be good to clarify the difference between pypam and pamguard.

As I understood it (but I'm not an expert), pypam is more about (pre)processing and managing files, and pamguard is to do the biological detections/classifications? 

Cheers
Lennert

**Comment by cparcerisas** [comment]
Well pypam and PAMguard can do similar things in a lot of aspects. The main difference is in how this software is used. pypam is built as a library which can be incorporated in other python processes, while PAMGuard is a stand-alone application. 
They also have some functionalities which are different, one being the classification/detection in PAMGuard which is not available in pypam.

**Comment by LennertSchepers** [comment]
Ok thanks for the quick answer @cparcerisas!
