### ISSUE TITLE
update readme to contain info about PBP

### ISSUE THREAD

**Issue by cparcerisas** [lifewatch/pypam#112]
Add to the pypam readme and readthedocs a page linking it to PBP https://github.com/mbari-org/pypam-based-processing so people hearing from SoundCoop about pypam don't get confused about what repository to use

**Comment by carueda** [comment]
Agree @cparcerisas.  Although the name of the PBP repo, as well as the README there make it clear that the processing is based on PyPAM, we could probably be more specific about the differences (eg., direct file/signal handling).  While we are looking into this, perhaps worth resuming our pending discussion about best strategies moving forward in terms of, for example, possibly integrating PBP functionality into PyPAM itself, or determining that it is good to have it as a separate tool, etc.   (cc @ryjombari @danellecline )

**Comment by cparcerisas** [comment]
Yes @carueda! I agree it's clear in PBP, but it is not clear in pypam so I think it is good to make it a 2-way street. 
So I will start by adding a very short paragraph on the readme, you can elaborate further if you want. 

Indeed, the talk about best strategies to move forward is still needed!

**Comment by cparcerisas** [comment]
@carueda  can you confirm the readme is ok now? Then I close this issue

**Comment by carueda** [comment]
@cparcerisas - confirmed! .... but, I just took the opportunity for a slight edit https://github.com/lifewatch/pypam/pull/135
