### ISSUE TITLE
Establish standard merged plots of daily hybrid millidecade band results

### ISSUE THREAD

**Issue by ryjombari** [lifewatch/pypam#41]
For the SoundCoop effort with NCEI (and going forward) we need standard daily plots to accompany daily NetCDF files of hybrid millidecade spectra.  The plots provide an overview of the results including time-dependent (spectrogram, ideally with day/night reference) and statistical summary (percentiles).

**Comment by ryjombari** [comment]
I tried the built-in plotting functions but am not able to run them yet:
In [75]: pypam.plots.plot_hmb_ltsa(D)
    ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[75], line 1
----> 1 pypam.plots.plot_hmb_ltsa(D)

AttributeError: module 'pypam.plots' has no attribute 'plot_hmb_ltsa'


In [76]: pctlev = np.array([1,10,25,50,75,90,99])
    ...: spd = pypam.util.compute_spd(D, percentiles=pctlev)
    ...: pypam.plots.plot_spd(spd, db=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[76], line 2
      1 pctlev = np.array([1,10,25,50,75,90,99])
----> 2 spd = pypam.util.compute_spd(D, percentiles=pctlev)
      3 pypam.plots.plot_spd(spd, db=True)

AttributeError: module 'pypam' has no attribute 'util'

**Comment by cparcerisas** [comment]
Fixed on commit bc3cdcb703789f1b75e559f5a9a0e89d159aec95
