### ISSUE TITLE
Set up poetry?

### ISSUE THREAD

**Issue by carueda** [lifewatch/pypam#6]
Hi Clea, would you be amenable to morphing the project setup to using [poetry](https://python-poetry.org/)? Though I haven't used it yet, I've heard very good things about it from various colleagues, and in fact I've been planning to use it in some of my python projects. Of course, no pressure at all and I'm aware there're other priorities at the moment, but we could opportunistically help in this way as well.

Hi @danellecline, could you share a bit of your poetry experience?

**Comment by danellecline** [comment]
@cparcerisas Poetry is great. It made it quite easy to setup to build and test in isolated environments.  I actually started with building my pip modules in the same manner as you have with pypam and was happy to switch.  It wasn't a huge effort and it has made maintaining my repos easier.

Here is an example of a pip package that I use poetry in for reference:

https://github.com/mbari-org/deepsea-ai

Note that the deepse-ai repo is for a command line tool, unlike pypam which is an API, but the setup is very similar.  This also pushes the package release to PyPam on new releases.  

If adding in the poetry build is of interest to you, please let us @carueda  @danellecline know.  We'd be happy to help with that if you are willing to add us as contributors to your pypam repo.  No pressure though.

~Danelle

**Comment by cparcerisas** [comment]
Hi Danelle, thanks for the info! I would definitely be interested in setting up poetry, especially if you are helping with it!
