### ISSUE TITLE
Signal oriented API?

### ISSUE THREAD

**Issue by carueda** [lifewatch/pypam#9]
Hi @cparcerisas – Given the potential disparity of file/directory organization (including time-stamping) practices "out there," I've been wondering if pypam could/should consider some expanded or adjusted API such that it also allows to be used directly on given signals (i.e., numpy or xarray arrays), that is, not necessarily with given wav files as input. I understand pypam has been mainly intended to help with file-oriented scenarios (in fact, that's even stated in the readme). However, having some separation of concerns (that is, file handing on one hand, and signal processing on the other) could prove useful in term of increased flexibility to accommodate a broader set of use cases. One example could be the handling of files where time keeping could be hard to make comply with some assumed structure or file organization. In this case, the file handling aspect would be addressed by user code, not by pypam. Complementary to this is the possible easier dispatch of parallel processing over multiple data "chunks."

Hope all that makes sense, but of course, happy to provide more details here while we get a chance to discuss further (maybe in a future pypam telecon). Thanks.

cc: @ryjombari, @danellecline

**Comment by cparcerisas** [comment]
Hi @carueda, thanks for your input. This is actually more or less already implemented. You could use something similar to the following code: 

`import numpy as np
import xarray
import matplotlib.pyplot as plt

import pypam.utils as utils
import pypam.signal as sig

N_CHUNKS = 5

# Create artificial data of 1 second
fs = 512000
test_freqs = [400, fs / 4]
samples = fs * N_CHUNKS
noise_amp = 100
signal_amp = 100
data = np.random.random(samples)
t = np.linspace(0, 1 - 1 / fs, samples)
phase = 2 * np.pi * t
for test_freq in test_freqs:
    data = data + signal_amp * np.sin(test_freq * phase)
# Set the nfft to 1 second
nfft = fs

# Loop through all your chunks
list_spectras = []
for i in np.arange(N_CHUNKS):
    s = sig.Signal(data, fs=fs)
    s.set_band(None)
    fbands, spectra, _ = s.spectrum(scaling='spectrum', nfft=fs, db=False, overlap=0, force_calc=True)
    list_spectras.append(spectra)

# Convert the spectra to a datarray
psd_da = xarray.DataArray(list_spectras, coords={'id': np.arange(N_CHUNKS), 'frequency': fbands}, dims=['id', 'frequency'])

# Get the millidecade bands
bands_limits, bands_c = utils.get_hybrid_millidecade_limits(band=[0, fs/2], nfft=nfft)
milli_psd = utils.psd_ds_to_bands(psd_da, bands_limits, bands_c, fft_bin_width=fs / nfft, db=False)

milli_psd.mean('id').plot()
plt.show()
`

Let me know if this is what you were looking for or if you would also like pypam to handle the looping through the chunks!

**Comment by carueda** [comment]
Hi @cparcerisas - that's great, and thanks for the detailed example! I will try exercising this with some real data.
